project_name: koomos

builds:
  - id: koomos
    main: ./main.go
    binary: koomos
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Pitchouneee
    name: koomos

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
